version: '3.8'

services:
  server:
    image: 'nginx:stable-alpine'
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
        - 8000:80



    # php:
    #     image: php
    # mysql:
    #     image: mysql
    # composer:
    # artisan:
    # npm:
