version: '3.8'
services:
  # backend:

  # frontend:

  mongodb:
    image: 'mongo'
    container_name: 'mongodb'
    volumes:
      - data:/data/db
    environment:
     # MONGO_INITDB_ROOT_USERNAME: admin (same as below)
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    # env_file:
    #   - './env/mongo.env'
    # networks:
    #   - 'goals-network' # all services in one docker compose file will have the same network
volumes:
  data:


# mongo db docker run
#  docker run --name mongodb --rm -d --network goals-network -v data:/data/db -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=12345678 mongo
# --rm and -d can be ignored in a docker-compose file
