FROM node:19-alpine

WORKDIR /app

ENTRYPOINT ["npm"]

# docker build -t node-util .
# docker run -it -v /Users/franklee/docker_playground/utility-container:/app node-util

# docker run -it -v /Users/franklee/docker_playground/utility-container:/app node-util install express

# docker-compose run --rm npm init
